--- Makefile.osx	2015-03-08 18:04:16.000000000 -0400
+++ Makefile.osx	2016-04-21 22:12:07.000000000 -0400
@@ -5,30 +5,13 @@
 include Makefile.srcs
 
 # General configuration variables:
-CC_PPC = gcc-4.0
-CC_I386 = gcc-4.0
-CC_X86_64 = gcc-4.0
-CPP_PPC = g++-4.0
-CPP_I386 = g++-4.0
-CPP_X86_64 = g++-4.0
-COMPILERFLAGS = -Os -fexceptions -fvisibility=hidden -DNO_LCMS
-COMPILERFLAGS_PPC = -arch ppc
-COMPILERFLAGS_I386 = -arch i386
+CC_X86_64 = $(CC)
+CPP_X86_64 = $(CXX)
+COMPILERFLAGS = -Oz -fexceptions -fvisibility=hidden -D__ANSI__ -mmacosx-version-min=10.10 -DDISABLE_PERF_MEASUREMENT $(CFLAGS)
 COMPILERFLAGS_X86_64 = -arch x86_64
-COMPILERPPFLAGS = -Wno-ctor-dtor-privacy
-INCLUDE += 
-INCLUDE_PPC = -isysroot /Developer/SDKs/MacOSX10.5.sdk
-INCLUDE_I386 = -isysroot /Developer/SDKs/MacOSX10.5.sdk
-INCLUDE_X86_64 = -isysroot /Developer/SDKs/MacOSX10.6.sdk
-CFLAGS_PPC = $(COMPILERFLAGS) $(COMPILERFLAGS_PPC) $(INCLUDE) $(INCLUDE_PPC)
-CFLAGS_I386 = $(COMPILERFLAGS) $(COMPILERFLAGS_I386) $(INCLUDE) $(INCLUDE_I386)
+COMPILERPPFLAGS = -Wno-ctor-dtor-privacy -D__ANSI__ -stdlib=libc++
 CFLAGS_X86_64 = $(COMPILERFLAGS) $(COMPILERFLAGS_X86_64) $(INCLUDE) $(INCLUDE_X86_64)
-CPPFLAGS_PPC = $(COMPILERPPFLAGS) $(CFLAGS_PPC)
-CPPFLAGS_I386 = $(COMPILERPPFLAGS) $(CFLAGS_I386)
 CPPFLAGS_X86_64 = $(COMPILERPPFLAGS) $(CFLAGS_X86_64)
-LIBRARIES_PPC = -Wl,-syslibroot /Developer/SDKs/MacOSX10.5.sdk
-LIBRARIES_I386 = -Wl,-syslibroot /Developer/SDKs/MacOSX10.5.sdk
-LIBRARIES_X86_64 = -Wl,-syslibroot /Developer/SDKs/MacOSX10.6.sdk
 LIBTOOL = libtool
 LIPO = lipo
 
@@ -38,12 +21,8 @@
 LIBNAME = lib$(TARGET).$(VER_MAJOR).dylib
 HEADER = Source/FreeImage.h
 
-.SUFFIXES: .o-ppc .o-i386 .o-x86_64
-MODULES_PPC = $(SRCS:.c=.o-ppc)
-MODULES_I386 = $(SRCS:.c=.o-i386)
+.SUFFIXES: .o-x86_64
 MODULES_X86_64 = $(SRCS:.c=.o-x86_64)
-MODULES_PPC := $(MODULES_PPC:.cpp=.o-ppc)
-MODULES_I386 := $(MODULES_I386:.cpp=.o-i386)
 MODULES_X86_64 := $(MODULES_X86_64:.cpp=.o-x86_64)
 
 PREFIX = /usr/local
@@ -52,55 +31,19 @@
 
 default: all
 
-all: dist
+all: FreeImage
 
-dist: FreeImage
-	mkdir -p Dist
-	cp *.a Dist/
-	cp *.dylib Dist/
-	cp Source/FreeImage.h Dist/
-
-FreeImage: $(STATICLIB) $(SHAREDLIB)
-
-$(STATICLIB): $(STATICLIB)-ppc $(STATICLIB)-i386 $(STATICLIB)-x86_64
-	$(LIPO) -create $(STATICLIB)-ppc $(STATICLIB)-i386 $(STATICLIB)-x86_64 -output $(STATICLIB)
-
-$(STATICLIB)-ppc: $(MODULES_PPC)
-	$(LIBTOOL) -arch_only ppc -o $@ $(MODULES_PPC)
-
-$(STATICLIB)-i386: $(MODULES_I386)
-	$(LIBTOOL) -arch_only i386 -o $@ $(MODULES_I386)
+FreeImage: $(STATICLIB)-x86_64 $(SHAREDLIB)-x86_64
 
 $(STATICLIB)-x86_64: $(MODULES_X86_64)
 	$(LIBTOOL) -arch_only x86_64 -o $@ $(MODULES_X86_64)
 
-$(SHAREDLIB): $(SHAREDLIB)-ppc $(SHAREDLIB)-i386 $(SHAREDLIB)-x86_64
-	$(LIPO) -create $(SHAREDLIB)-ppc $(SHAREDLIB)-i386 $(SHAREDLIB)-x86_64 -output $(SHAREDLIB)
-
-$(SHAREDLIB)-ppc: $(MODULES_PPC)
-	$(CPP_PPC) -arch ppc -dynamiclib $(LIBRARIES_PPC) -o $@ $(MODULES_PPC)
-
-$(SHAREDLIB)-i386: $(MODULES_I386)
-	$(CPP_I386) -arch i386 -dynamiclib $(LIBRARIES_I386) -o $@ $(MODULES_I386)
-
 $(SHAREDLIB)-x86_64: $(MODULES_X86_64)
-	$(CPP_X86_64) -arch x86_64 -dynamiclib $(LIBRARIES_X86_64) -o $@ $(MODULES_X86_64)
-
-.c.o-ppc:
-	$(CC_PPC) $(CFLAGS_PPC) -c $< -o $@
-
-.c.o-i386:
-	$(CC_I386) $(CFLAGS_I386) -c $< -o $@
+	$(CPP_X86_64) -arch x86_64 -dynamiclib $(LIBRARIES_X86_64) -o $@ $(MODULES_X86_64) Source/LibJPEG/.libs/libturbojpeg.a
 
 .c.o-x86_64:
 	$(CC_X86_64) $(CFLAGS_X86_64) -c $< -o $@
 
-.cpp.o-ppc:
-	$(CPP_PPC) $(CPPFLAGS_PPC) -c $< -o $@
-
-.cpp.o-i386:
-	$(CPP_I386) $(CPPFLAGS_I386) -c $< -o $@
-
 .cpp.o-x86_64:
 	$(CPP_X86_64) $(CPPFLAGS_X86_64) -c $< -o $@
 
@@ -112,4 +55,4 @@
 	ln -sf $(SHAREDLIB) $(INSTALLDIR)/$(LIBNAME)
 
 clean:
-	rm -f core Dist/*.* u2dtmp* $(MODULES_PPC) $(MODULES_I386) $(MODULES_X86_64) $(STATICLIB) $(STATICLIB)-ppc $(STATICLIB)-i386 $(SHAREDLIB) $(SHAREDLIB)-ppc $(SHAREDLIB)-i386 $(SHAREDLIB)-x86_64
+	rm -f core Dist/*.* u2dtmp* $(MODULES_X86_64) $(STATICLIB) $(STATICLIB)-x86_64 $(SHAREDLIB) $(SHAREDLIB)-x86_64
